sudo: false
language: cpp
compiler: gcc
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install:
 - "echo 'ac_add_options --with-taglib-source=packaged' >> nightingale.config"
 - "echo 'ac_add_options --enable-tests' >> nightingale.config"
script: "./build.sh && make test"
branches:
  only:
    - sb-trunk-oldxul
notifications:
  email:
    on_success: change
    on_failure: change
  irc: "irc.mozilla.org#nightingale"
addons:
  apt:
    packages:
    - autoconf
    - libgtk2.0-dev
    - libdbus-glib-1-dev
#    - libtag1-dev
    - libgstreamer-plugins-base0.10-dev
    - zip
    - unzip
    - gstreamer0.10-plugins-base
    - gstreamer0.10-alsa
    - gstreamer0.10-x
    - gstreamer0.10-plugins-good
#    - gstreamer0.10-plugins-bad
#    - gstreamer0.10-plugins-ugly
#    - gstreamer0.10-ffmpeg
#    - gtk2-engines-pixbuf
#    - lib-idl-dev
#    - ibasound2-dev

